"""Stage 4: PixInsight - BlurXTerminator (deconvolution) + NoiseXTerminator on each linear stack.

Generates one PJSR script for all groups and runs PixInsight headless:
    PixInsight.exe --automation-mode -n --no-splash -r=<script> --force-exit
Progress is reported through files because a headless PixInsight has no console we can read.
"""
import os, json, time, subprocess
import numpy as np
import tifffile

JS_TEMPLATE = r"""
// generated by MoonStack
var jobs = %(jobs)s;
var logPath = %(log)s;
var donePath = %(done)s;
var log = "";
function L(s) { log += s + "\n"; File.writeTextFile(logPath, log); }
try {
  for (var i = 0; i < jobs.length; ++i) {
    var j = jobs[i];
    var t0 = Date.now();
    var ws = ImageWindow.open(j.src);
    if (ws.length == 0) { L("FAILED to open " + j.src); continue; }
    var w = ws[0]; var v = w.mainView;
    if (j.bxt) {
      var P = new BlurXTerminator;
      P.correct_only = false; P.sharpen_stars = 0; P.adjust_halos = 0;
      P.auto_nonstellar_psf = false; P.nonstellar_psf_diameter = j.psf;
      P.sharpen_nonstellar = j.sharpen; P.lum_only = false;
      if (!P.executeOn(v)) L("  BXT failed on " + j.name);
    }
    if (j.nxt > 0) {
      var N = new NoiseXTerminator;
      N.denoise = j.nxt; N.detail = j.detail; N.iterations = 2;
      if (!N.executeOn(v)) L("  NXT failed on " + j.name);
    }
    if (!w.saveAs(j.dst, false, false, false, false)) L("  save failed " + j.dst);
    w.forceClose();
    L(j.name + " ok " + ((Date.now() - t0) / 1000).toFixed(1) + "s");
  }
} catch (e) {
  L("ERROR " + e);
}
File.writeTextFile(donePath, "done");
"""


def _js(s):
    return json.dumps(str(s).replace("\\", "/"))


def run(cfg, groups, log=print):
    exe = cfg["pixinsight_exe"]
    if not os.path.exists(exe):
        log(f"[pixinsight] not found: {exe} - skipping"); return groups
    indir = os.path.join(cfg["output_dir"], "pi_in"); outdir = os.path.join(cfg["output_dir"], "pi_out")
    os.makedirs(indir, exist_ok=True); os.makedirs(outdir, exist_ok=True)
    jobs = []
    for g in groups:
        if not g.get("stack"):
            continue
        img = tifffile.imread(g["stack"]).astype(np.float32)
        top = float(img.max())
        img = np.clip(img / (top * 1.02), 0, 1) if top > 0 else img
        src = os.path.abspath(os.path.join(indir, g["name"] + ".tif"))
        dst = os.path.abspath(os.path.join(outdir, g["name"] + ".tif"))
        tifffile.imwrite(src, img, photometric="rgb")
        few = g["n_stacked"] < 4
        # brackets carry the sunlit sliver in single short frames: denoise gently to keep its texture
        nxt = cfg["nxt"]["denoise_total"] if ((g["long"] or few) and g["kind"] != "bracket") else cfg["nxt"]["denoise"]
        jobs.append(dict(name=g["name"], src=src.replace("\\", "/"), dst=dst.replace("\\", "/"),
                         bxt=bool(cfg["bxt"]["enabled"]), psf=cfg["bxt"]["nonstellar_psf_diameter"],
                         sharpen=cfg["bxt"]["sharpen_nonstellar"],
                         nxt=(nxt if cfg["nxt"]["enabled"] else 0), detail=cfg["nxt"]["detail"]))
        g["pi_scale"] = top * 1.02
        g["pi_out"] = dst
    script = os.path.abspath(os.path.join(cfg["output_dir"], "pixinsight_job.js"))
    logp = os.path.abspath(os.path.join(cfg["output_dir"], "pixinsight_job.log"))
    done = os.path.abspath(os.path.join(cfg["output_dir"], "pixinsight_job.done"))
    for p in (logp, done):
        if os.path.exists(p):
            os.remove(p)
    with open(script, "w", encoding="utf-8") as f:
        f.write(JS_TEMPLATE % dict(jobs=json.dumps(jobs, indent=1), log=_js(logp), done=_js(done)))
    log(f"[pixinsight] {len(jobs)} images -> BXT(sharpen {cfg['bxt']['sharpen_nonstellar']}) + NXT; launching...")
    proc = subprocess.Popen([exe, "--automation-mode", "-n", "--no-splash",
                             "-r=" + script.replace("\\", "/"), "--force-exit"],
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    t0 = time.time(); seen = 0
    while not os.path.exists(done):
        if time.time() - t0 > 1800:
            log("[pixinsight] TIMEOUT after 30 min; killing"); proc.kill(); break
        if os.path.exists(logp):
            lines = open(logp, encoding="utf-8", errors="ignore").read().splitlines()
            for ln in lines[seen:]:
                log("   PI: " + ln)
            seen = len(lines)
        time.sleep(2)
    if os.path.exists(logp):
        for ln in open(logp, encoding="utf-8", errors="ignore").read().splitlines()[seen:]:
            log("   PI: " + ln)
    try:
        proc.wait(timeout=90)
    except subprocess.TimeoutExpired:
        proc.kill()
    for g in groups:
        if g.get("pi_out") and not os.path.exists(g["pi_out"]):
            log(f"[pixinsight] no output for {g['name']}, will use raw stack")
            g["pi_out"] = None
    log(f"[pixinsight] finished in {time.time() - t0:.0f}s")
    with open(os.path.join(cfg["output_dir"], "groups.json"), "w", encoding="utf-8") as f:
        json.dump(groups, f, indent=1, ensure_ascii=False)
    return groups
