"""Stage 6: Photoshop - layered PSD per phase (stack + sharpen layer + neutral Curves /
Vibrance adjustment layers for hand tweaking) and a layered composite PSD of the whole
eclipse. Runs an ExtendScript via `Photoshop.exe script.jsx`.
"""
import os, json, time, subprocess

JSX_TEMPLATE = r"""
// generated by MoonStack
#target photoshop
app.displayDialogs = DialogModes.NO;
var jobs = %(jobs)s;
var comp = %(comp)s;
var unsharp = %(unsharp)s;
var logPath = %(log)s, donePath = %(done)s;
var log = "";
function L(s) { log += s + "\n"; var f = new File(logPath); f.open("w"); f.write(log); f.close(); }
function addAdjustment(kind) {
  try {
    var d = new ActionDescriptor(); var r = new ActionReference();
    r.putClass(stringIDToTypeID("adjustmentLayer")); d.putReference(charIDToTypeID("null"), r);
    var d2 = new ActionDescriptor(); var d3 = new ActionDescriptor();
    d3.putEnumerated(stringIDToTypeID("presetKind"), stringIDToTypeID("presetKindType"), stringIDToTypeID("presetKindDefault"));
    d2.putObject(charIDToTypeID("Type"), stringIDToTypeID(kind), d3);
    d.putObject(charIDToTypeID("Usng"), stringIDToTypeID("adjustmentLayer"), d2);
    executeAction(charIDToTypeID("Mk  "), d, DialogModes.NO);
    app.activeDocument.activeLayer.name = kind;
  } catch (e) { L("  adjustment " + kind + " failed: " + e); }
}
// Photoshop 26.x: after the first document, DOM app.open() reports "open options are
// incorrect" (seen on this machine while the subscription was not yet active). The Action
// Manager path is more tolerant, and we verify the opened document is really the file asked for.
function openFile(path) {
  var f = new File(path);
  try { var d = app.open(f); if (d.name == f.name) return d; d.close(SaveOptions.DONOTSAVECHANGES); } catch (e) {}
  var desc = new ActionDescriptor(); desc.putPath(charIDToTypeID("null"), f);
  executeAction(charIDToTypeID("Opn "), desc, DialogModes.NO);
  var d = app.activeDocument;
  if (d.name != f.name) { throw new Error("opened wrong document: " + d.name + " for " + path); }
  return d;
}
function saveJpg(doc, path) {
  var o = new JPEGSaveOptions(); o.quality = 11; o.embedColorProfile = true;
  doc.saveAs(new File(path), o, true, Extension.LOWERCASE);
}
try {
  for (var i = 0; i < jobs.length; ++i) {
    var j = jobs[i];
    var doc = openFile(j.tif);
    doc.bitsPerChannel = BitsPerChannelType.SIXTEEN;
    var base = doc.activeLayer; base.name = "Stack";
    var sh = base.duplicate(); sh.name = "Sharpen (unsharp mask)";
    doc.activeLayer = sh;
    sh.applyUnSharpMask(unsharp.amount, unsharp.radius, unsharp.threshold);
    addAdjustment("curves");
    addAdjustment("vibrance");
    var pso = new PhotoshopSaveOptions(); pso.layers = true; pso.embedColorProfile = true;
    doc.saveAs(new File(j.psd), pso, true, Extension.LOWERCASE);
    doc.flatten();
    doc.bitsPerChannel = BitsPerChannelType.EIGHT;
    saveJpg(doc, j.jpg);
    doc.close(SaveOptions.DONOTSAVECHANGES);
    L(j.name + " ok");
  }
  if (comp) {
    var black = new SolidColor(); black.rgb.red = 0; black.rgb.green = 0; black.rgb.blue = 0;
    app.backgroundColor = black;
    var cd = app.documents.add(comp.W, comp.H, 300, "Eclipse sequence", NewDocumentMode.RGB, DocumentFill.BACKGROUNDCOLOR);
    for (var i = 0; i < comp.items.length; ++i) {
      var it = comp.items[i];
      var src = openFile(it.jpg);
      src.crop([it.crop_x, it.crop_y, it.crop_x + it.crop_size, it.crop_y + it.crop_size]);
      src.resizeImage(UnitValue(it.w, "px"), UnitValue(it.h, "px"), null, ResampleMethod.BICUBICSHARPER);
      src.selection.selectAll(); src.selection.copy(); src.close(SaveOptions.DONOTSAVECHANGES);
      app.activeDocument = cd;
      var lay = cd.paste(); lay.name = it.name;
      var b = lay.bounds;
      lay.translate(it.x - b[0].as("px"), it.y - b[1].as("px"));
    }
    var pso2 = new PhotoshopSaveOptions(); pso2.layers = true;
    cd.saveAs(new File(comp.psd), pso2, true, Extension.LOWERCASE);
    cd.flatten(); saveJpg(cd, comp.jpg);
    cd.close(SaveOptions.DONOTSAVECHANGES);
    L("composite ok");
  }
} catch (e) { L("ERROR " + e + " line " + e.line + " -- Photoshop stage incomplete; rerun `python run.py --stage photoshop` once Photoshop opens files normally"); }
var f = new File(donePath); f.open("w"); f.write("done"); f.close();
"""


def _js(s):
    return json.dumps(str(s).replace("\\", "/"))


def run(cfg, groups, log=print):
    exe = cfg["photoshop_exe"]
    if not os.path.exists(exe):
        log(f"[photoshop] not found: {exe} - skipping"); return groups
    outdir = os.path.abspath(os.path.join(cfg["output_dir"], "photoshop"))
    os.makedirs(outdir, exist_ok=True)
    jobs = []
    for g in groups:
        if not g.get("final_tif"):
            continue
        j = dict(name=g["name"], tif=os.path.abspath(g["final_tif"]).replace("\\", "/"),
                 psd=os.path.join(outdir, g["name"] + ".psd").replace("\\", "/"),
                 jpg=os.path.join(outdir, g["name"] + ".jpg").replace("\\", "/"))
        jobs.append(j)
        g["psd"] = j["psd"]
    comp = None
    cpath = os.path.join(cfg["output_dir"], "composite.json")
    if os.path.exists(cpath):
        comp = json.load(open(cpath, encoding="utf-8"))
        for it in comp["items"]:
            it["jpg"] = os.path.abspath(it["jpg"]).replace("\\", "/")
        comp["psd"] = os.path.join(outdir, "00_eclipse_sequence.psd").replace("\\", "/")
        comp["jpg"] = os.path.join(outdir, "00_eclipse_sequence.jpg").replace("\\", "/")
    script = os.path.abspath(os.path.join(cfg["output_dir"], "photoshop_job.jsx"))
    logp = os.path.abspath(os.path.join(cfg["output_dir"], "photoshop_job.log"))
    done = os.path.abspath(os.path.join(cfg["output_dir"], "photoshop_job.done"))
    for p in (logp, done):
        if os.path.exists(p):
            os.remove(p)
    with open(script, "w", encoding="utf-8") as f:
        f.write(JSX_TEMPLATE % dict(jobs=json.dumps(jobs, indent=1), comp=json.dumps(comp),
                                    unsharp=json.dumps(cfg["ps_unsharp"]), log=_js(logp), done=_js(done)))
    log(f"[photoshop] {len(jobs)} PSDs + composite; launching Photoshop...")
    subprocess.Popen([exe, script], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    t0 = time.time(); seen = 0
    while not os.path.exists(done):
        if time.time() - t0 > 1200:
            log("[photoshop] TIMEOUT after 20 min"); break
        if os.path.exists(logp):
            lines = open(logp, encoding="utf-8", errors="ignore").read().splitlines()
            for ln in lines[seen:]:
                log("   PS: " + ln)
            seen = len(lines)
        time.sleep(2)
    if os.path.exists(logp):
        for ln in open(logp, encoding="utf-8", errors="ignore").read().splitlines()[seen:]:
            log("   PS: " + ln)
    log(f"[photoshop] finished in {time.time() - t0:.0f}s -> {outdir}")
    with open(os.path.join(cfg["output_dir"], "groups.json"), "w", encoding="utf-8") as f:
        json.dump(groups, f, indent=1, ensure_ascii=False)
    return groups
